# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 878a9f4c057c61e55639db3bf633d31b54c0596e045c84c1d2f0a05c42bac2d809c482203817b49787383048a7cbf900b0691cfada35b79db811b63d73d66c67

test:
  secret_key_base: ac92ff18e7dcc2ce3a228e7a71f6a244896acc8f39b0ec1cdff11287702d3f4fb7686a8c77ae49527f3b6dad9652b88b8a6b54d6825d3f044932e39b9c34a665

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
